stages:
  - build

variables:
  # Move cargo home to the project directory so it can be cached
  CARGO_HOME: $CI_PROJECT_DIR/.cargo_home

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo_home/bin
    - .cargo_home/registry/index
    - .cargo_home/registry/cache
    - .cargo_home/git/db
    - firmware/target/

build-firmware:
  stage: build
  image: rust:latest
  before_script:
    - apt-get update && apt-get install -y libudev-dev
    # Add cargo bin to path so we can use flip-link
    - export PATH="$CARGO_HOME/bin:$PATH"
    # Run project setup script
    - cd firmware
    - chmod +x setup.sh
    - ./setup.sh
  script:
    - cd firmware
    - cargo check # Fast check for errors
    - cargo build --release # Full build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
