/*
 * VS_OrientationEstimation.h
 *
 *  Created on: Jul. 20, 2023
 *      Author: aloehr
 */

#ifndef INC_APPLICATION_CONTROL_VIRTUALSENSORS_VS_ORIENTATIONESTIMATION_H_
#define INC_APPLICATION_CONTROL_VIRTUALSENSORS_VS_ORIENTATIONESTIMATION_H_



#endif /* INC_APPLICATION_CONTROL_VIRTUALSENSORS_VS_ORIENTATIONESTIMATION_H_ */
