M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Tue 06 Feb 2024 08:51:50 PM EST
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-06T20:51:50-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.850
%
G90
G05
T1
X119.975Y-71.346
X122.096Y-69.225
M30
